### Loading Data and make first row column headers

In [4]:
import pandas as pd
import numpy as np

stocks = pd.read_csv('stocks.csv', sep=r'\s*,\s*', header=0, encoding='ascii', engine='python')

### Add New columns with the difference in 30 minute intervals starting at noon

In [17]:
stocks['Diff12-12:30'] = stocks['12:30'] - stocks['noon']
stocks['Diff12:30-1'] = stocks['1'] - stocks['12:30']
stocks['Diff1-1:30'] = stocks['1:30'] - stocks['1']
stocks['Diff1:30-2'] = stocks['2'] - stocks['1:30']
stocks['Diff2-2:30'] = stocks['2:30'] - stocks['2']
stocks['Diff2:30-3'] = stocks['3'] - stocks['2:30']
stocks['Diff3-3:30'] = stocks['3:30'] - stocks['3']
stocks['Diff3:30-4'] = stocks['4'] - stocks['3:30']
stocks['Diff12-4'] = stocks['4'] - stocks['noon']
stocks1 = stocks[['ticker','date','Diff12-12:30','Diff12:30-1','Diff1-1:30','Diff1:30-2','Diff2-2:30', 'Diff2:30-3', 'Diff3-3:30', 'Diff3:30-4', 'Diff12-4']]
print(stocks1)

      ticker        date  Diff12-12:30  Diff12:30-1  Diff1-1:30  Diff1:30-2  \
0          A  2020-09-04         -0.56        -0.44        0.16       -0.16
1          A  2020-09-05         -0.04         0.26       -0.51        0.18
2         AA  2020-08-18         -0.21        -0.27        0.07       -0.61
3         AA  2020-08-22          0.27        -0.61        0.20       -0.40
4         AA  2020-08-26         -0.19         0.06        0.13        0.07
...      ...         ...           ...          ...         ...         ...
58127   ZYXI  2020-09-16          0.18         0.62       -0.18        0.24
58128   ZYXI  2020-09-19          1.38        -0.86       -0.58       -0.86
58129   ZYXI  2020-09-22          0.53        -0.18       -1.06       -1.60
58130   ZYXI  2020-09-29          0.06         0.36        0.23        1.07
58131   ZYXI  2020-10-03          1.82        -0.74        0.51       -0.74

       Diff2-2:30  Diff2:30-3  Diff3-3:30  Diff3:30-4  Diff12-4
0           -0.04       -0.03       -0.34        0.51     -0.90
1            0.21        0.61       -0.15       -0.36      0.20
2            0.07       -0.14        0.00        0.82     -0.27
3            0.00        0.07       -0.20        0.40     -0.27
4           -0.07        0.20        0.53        0.27      1.00
...           ...         ...         ...         ...       ...
58127       -0.61       -1.55        1.48        0.56      0.74
58128        0.23        0.35        1.32       -0.75      0.23
58129        0.59       -0.29        0.83        0.53     -0.65
58130        0.29       -0.23        0.65        0.29      2.72
58131        0.18        0.11        0.34       -0.91      0.57

[58132 rows x 11 columns]

### Group by tickers with the most occurrences

In [32]:
stocks2 = stocks1.groupby('ticker').size().sort_values(ascending = False).reset_index(name='ocurrences')
print (stocks2)

     ticker  ocurrences
0       RRD          44
1      NCLH          34
2      SAVE          32
3      UNFI          32
4      GOLD          30
...     ...         ...
5302   HVBC           1
5303    HPI           1
5304   HMNF           1
5305    HMG           1
5306    JPC           1

[5307 rows x 2 columns]

### Get grouped by count where difference is >0.5 by ticker

In [18]:
## group by and count occurences of a difference of 0.5 or more for each ticker
                                                
stocks3 = stocks1[stocks1['Diff12-12:30'] > 0.5].groupby('ticker', as_index = False)['Diff12-12:30'].count()
stocks6 = stocks1[stocks1['Diff12:30-1'] > 0.5].groupby('ticker', as_index = False)['Diff12:30-1'].count()
stocks7 = stocks1[stocks1['Diff1-1:30'] > 0.5].groupby('ticker', as_index = False)['Diff1-1:30'].count()
stocks8 = stocks1[stocks1['Diff1:30-2'] > 0.5].groupby('ticker', as_index = False)['Diff1:30-2'].count()
stocks9 = stocks1[stocks1['Diff2-2:30'] > 0.5].groupby('ticker', as_index = False)['Diff2-2:30'].count()
stocks10 = stocks1[stocks1['Diff2:30-3'] > 0.5].groupby('ticker', as_index = False)['Diff2:30-3'].count()
stocks11 = stocks1[stocks1['Diff3-3:30'] > 0.5].groupby('ticker', as_index = False)['Diff3-3:30'].count()
stocks12 = stocks1[stocks1['Diff3:30-4'] > 0.5].groupby('ticker', as_index = False)['Diff3:30-4'].count()
stocks13 = stocks1[stocks1['Diff12-4'] > 0.5].groupby('ticker', as_index = False)['Diff12-4'].count()

## Sort these by the count
stocks4 = stocks3.sort_values(by=['Diff12-12:30'], ascending=False)
stocks66 = stocks6.sort_values(by=['Diff12:30-1'], ascending=False)
stocks77 = stocks7.sort_values(by=['Diff1-1:30'], ascending=False)
stocks88 = stocks8.sort_values(by=['Diff1:30-2'], ascending=False)
stocks99 = stocks9.sort_values(by=['Diff2-2:30'], ascending=False)
stocks1010 = stocks10.sort_values(by=['Diff2:30-3'], ascending=False)
stocks1111 = stocks11.sort_values(by=['Diff3-3:30'], ascending=False)
stocks1212 = stocks12.sort_values(by=['Diff3:30-4'], ascending=False)
stocks1313 = stocks13.sort_values(by=['Diff12-4'], ascending=False)

### Merge Total Count Dataset with Total Count where Diff >0.5 Dataset

In [20]:
stocks5 = pd.merge(stocks4, stocks2, on="ticker")
stocks5['patternpercentage'] = stocks5['Diff12-12:30']/stocks5['ocurrences']
stocks5sorted = stocks5.sort_values(by=['patternpercentage'], ascending=False)

stocks666 = pd.merge(stocks66, stocks2, on="ticker")
stocks666['patternpercentage'] = stocks666['Diff12:30-1']/stocks666['ocurrences']
stocks666sorted = stocks666.sort_values(by=['patternpercentage'], ascending=False)

stocks777 = pd.merge(stocks77, stocks2, on="ticker")
stocks777['patternpercentage'] = stocks777['Diff1-1:30']/stocks777['ocurrences']
stocks777sorted = stocks777.sort_values(by=['patternpercentage'], ascending=False)

stocks888 = pd.merge(stocks88, stocks2, on="ticker")
stocks888['patternpercentage'] = stocks888['Diff1:30-2']/stocks888['ocurrences']
stocks888sorted = stocks888.sort_values(by=['patternpercentage'], ascending=False)

stocks999 = pd.merge(stocks99, stocks2, on="ticker")
stocks999['patternpercentage'] = stocks999['Diff2-2:30']/stocks999['ocurrences']
stocks999sorted = stocks999.sort_values(by=['patternpercentage'], ascending=False)

stocks101010 = pd.merge(stocks1010, stocks2, on="ticker")
stocks101010['patternpercentage'] = stocks101010['Diff2:30-3']/stocks101010['ocurrences']
stocks101010sorted = stocks101010.sort_values(by=['patternpercentage'], ascending=False)

stocks111111 = pd.merge(stocks1111, stocks2, on="ticker")
stocks111111['patternpercentage'] = stocks111111['Diff3-3:30']/stocks111111['ocurrences']
stocks111111sorted = stocks111111.sort_values(by=['patternpercentage'], ascending=False)

stocks121212 = pd.merge(stocks1212, stocks2, on="ticker")
stocks121212['patternpercentage'] = stocks121212['Diff3:30-4']/stocks121212['ocurrences']
stocks121212sorted = stocks121212.sort_values(by=['patternpercentage'], ascending=False)

stocks131313 = pd.merge(stocks1313, stocks2, on="ticker")
stocks131313['patternpercentage'] = stocks131313['Diff12-4']/stocks131313['ocurrences']
stocks131313sorted = stocks131313.sort_values(by=['patternpercentage'], ascending=False)

In [9]:
stocks5sorted[stocks5sorted.ocurrences > 10].head(50)

    ticker  Diff12-12:30  ocurrences  patternpercentage
8     SAVA            12          14           0.857143
2     MVIS            14          20           0.700000
10    HTGM            12          18           0.666667
6     WKHS            12          18           0.666667
11    CCCL            11          17           0.647059
288   XERS             7          11           0.636364
24     FET            10          16           0.625000
33    MEOH            10          16           0.625000
74    VIST             8          13           0.615385
96     TGS             8          13           0.615385
46    ETON             9          15           0.600000
57    AUTO             9          15           0.600000
16     CIH            10          17           0.588235
18    CKPT            10          17           0.588235
19    LQDA            10          17           0.588235
34    NBLX            10          17           0.588235
263   CVGI             7          12           0.583333
280   PDCO             7          12           0.583333
235   SBOW             7          12           0.583333
12     PHX            11          19           0.578947
133   NNVC             8          14           0.571429
123   PLCE             8          14           0.571429
137   QUMU             8          14           0.571429
138   HDSN             8          14           0.571429
72     BGI             9          16           0.562500
42    PLAY             9          16           0.562500
32    CPST            10          18           0.555556
419   PSNL             6          11           0.545455
452   CNTY             6          11           0.545455
451   ACLS             6          11           0.545455
447   SCVL             6          11           0.545455
520   IRMD             6          11           0.545455
328    GPP             6          11           0.545455
374    SSY             6          11           0.545455
410    GMO             6          11           0.545455
3     LINC            13          24           0.541667
230    FSM             7          13           0.538462
176   VRTV             7          13           0.538462
271   DOYU             7          13           0.538462
149    MIK             7          13           0.538462
233   FNKO             7          13           0.538462
251    RES             7          13           0.538462
81    SBPH             8          15           0.533333
51    MTDR             9          17           0.529412
30     RGS            10          19           0.526316
4      CEI            13          25           0.520000
371   GWRS             6          12           0.500000
22    DGLY            10          20           0.500000
155   MCRB             7          14           0.500000
210   RLGT             7          14           0.500000

In [10]:
stocks666sorted[stocks666sorted.ocurrences > 10].head(15)

    ticker  Diff12:30-1  ocurrences  patternpercentage
50      UG            8          11           0.727273
23     OFS            9          13           0.692308
32    FMCI            9          14           0.642857
53    RICK            8          13           0.615385
33    HGSH            9          15           0.600000
12    BRQS           10          18           0.555556
13    UONE           10          18           0.555556
10    IMRN           10          18           0.555556
2     TRNX           12          22           0.545455
119   SIFY            7          13           0.538462
158    DDS            7          13           0.538462
104   TENX            7          13           0.538462
141   ESTA            7          13           0.538462
127   GSUM            7          13           0.538462
124    GSM            7          13           0.538462

In [11]:
stocks777sorted[stocks777sorted.ocurrences > 10].head(15)

    ticker  Diff1-1:30  ocurrences  patternpercentage
13    EVLO          10          13           0.769231
31    KIRK           9          14           0.642857
0     QUAD          14          23           0.608696
28    EDRY           9          15           0.600000
62    QUMU           8          14           0.571429
1     ENTX          12          21           0.571429
21    AKTX           9          16           0.562500
214   CDLX           6          11           0.545455
194   SYNC           6          11           0.545455
317    JVA           6          11           0.545455
211   PSNL           6          11           0.545455
111   NTLA           7          13           0.538462
74    GTIM           8          15           0.533333
46    FORD           8          15           0.533333
4     NDRA          11          21           0.523810

In [12]:
stocks888sorted[stocks888sorted.ocurrences > 10].head(15)

    ticker  Diff1:30-2  ocurrences  patternpercentage
32    IIIV           9          14           0.642857
110   SGMA           7          11           0.636364
186   SMTX           7          11           0.636364
106   MRLN           8          13           0.615385
61     BRN           8          13           0.615385
62    EVSI           8          13           0.615385
10     AFI          10          17           0.588235
143    PSV           7          12           0.583333
6      SPI          11          19           0.578947
103   EPIX           8          14           0.571429
72    VRCA           8          14           0.571429
26    CLSD           9          16           0.562500
38    AQST           9          16           0.562500
20    DMTK          10          18           0.555556
218   MORF           6          11           0.545455

In [13]:
stocks999sorted[stocks999sorted.ocurrences > 10].head(15)

    ticker  Diff2-2:30  ocurrences  patternpercentage
34    OTIC           9          13           0.692308
21    REDU           9          13           0.692308
2     FLUX          11          16           0.687500
10    APPS          10          15           0.666667
16    HIHO           9          15           0.600000
7     ASPN          10          17           0.588235
158   NWHM           7          12           0.583333
176    MXC           7          12           0.583333
9     NURO          10          18           0.555556
319   XERS           6          11           0.545455
230   GLYC           6          11           0.545455
66     RFP           8          15           0.533333
35      HX           9          17           0.529412
12    MDWD          10          19           0.526316
49    DLPN           8          16           0.500000

In [14]:
stocks101010sorted[stocks101010sorted.ocurrences > 10].head(15)

    ticker  Diff2:30-3  ocurrences  patternpercentage
23    SSNT           9          15           0.600000
18     ISR           9          15           0.600000
39    RDVT           8          14           0.571429
3     MARA          10          18           0.555556
331   NVTA           6          11           0.545455
306   GLYC           6          11           0.545455
137   ARPO           7          13           0.538462
127   USAK           7          13           0.538462
98    KDMN           7          13           0.538462
0     RAVE          14          26           0.538462
49   CRESY           8          15           0.533333
77    AVGR           8          15           0.533333
73    RMBL           8          15           0.533333
11    LPCN          10          19           0.526316
171   QUMU           7          14           0.500000

In [15]:
stocks111111sorted[stocks111111sorted.ocurrences > 10].head(15)

    ticker  Diff3-3:30  ocurrences  patternpercentage
14    BLCM          10          15           0.666667
32    SAVA           9          14           0.642857
59     BRT           8          13           0.615385
37    TRCH           9          15           0.600000
400    FTK           6          11           0.545455
338   CNTY           6          11           0.545455
310   PSNL           6          11           0.545455
356   PSTI           6          11           0.545455
370   ATIF           6          11           0.545455
277   TSLA           6          11           0.545455
216   XERS           6          11           0.545455
2     TRNX          12          22           0.545455
173    DDS           7          13           0.538462
135   MYOS           7          13           0.538462
148   AIHS           7          13           0.538462

In [16]:
stocks121212sorted[stocks121212sorted.ocurrences > 10].head(50)

    ticker  Diff3:30-4  ocurrences  patternpercentage
24     SPN          10          13           0.769231
57    RIBT           9          13           0.692308
15    OPTT          11          16           0.687500
21    MLND          10          15           0.666667
100   SBOW           8          12           0.666667
115   STIM           8          13           0.615385
31     TGB          10          17           0.588235
23    MMLP          10          17           0.588235
214   ZYNE           7          12           0.583333
146    BBW           7          12           0.583333
8     SMHI          11          19           0.578947
14    KLDO          11          19           0.578947
86    RLGT           8          14           0.571429
73    KIRK           8          14           0.571429
58    PFSW           9          16           0.562500
1      NOG          14          25           0.560000
39    VERI          10          18           0.555556
42    NXTD          10          18           0.555556
10     GLG          11          20           0.550000
229   FTSI           6          11           0.545455
4     XELA          12          22           0.545455
304   GPRE           6          11           0.545455
3     CHFS          12          22           0.545455
361   EXPI           6          11           0.545455
173   VLRS           7          13           0.538462
174   IDYA           7          13           0.538462
151     NX           7          13           0.538462
124   PEIX           7          13           0.538462
182   LITB           7          13           0.538462
97    OTLK           8          15           0.533333
87    VRAY           8          15           0.533333
91     MWK           8          15           0.533333
45    CKPT           9          17           0.529412
29    VTGN          10          19           0.526316
32    SOLY          10          19           0.526316
22    ETTX          10          19           0.526316
13    VISL          11          21           0.523810
7     BLNK          11          21           0.523810
5      ZVO          12          23           0.521739
2     SCON          14          27           0.518519
134   CARV           7          14           0.500000
125   FMCI           7          14           0.500000
119   IMMP           7          14           0.500000
207   MESO           7          14           0.500000
143   EYES           7          14           0.500000
364   NSSC           6          12           0.500000
284   YRCW           6          12           0.500000
269    TRQ           6          12           0.500000
203   DPHC           7          14           0.500000
197   KMPH           7          14           0.500000

In [29]:
noonto4 = stocks131313sorted[stocks131313sorted.ocurrences > 10].head(50)
print(noonto4)

    ticker  Diff12-4  ocurrences  patternpercentage
122   SBOW        10          12           0.833333
349   GILT         9          11           0.818182
26    EVRI        12          15           0.800000
7     TRIL        14          18           0.777778
145    IVC        10          13           0.769231
104   RICK        10          13           0.769231
176   AVID        10          13           0.769231
420   GDEN         8          11           0.727273
440   SCVL         8          11           0.727273
471   PSNL         8          11           0.727273
481   ADPT         8          11           0.727273
186   FAMI        10          14           0.714286
175    CIO        10          14           0.714286
168     VG        10          14           0.714286
136   HRTG        10          14           0.714286
147   CARV        10          14           0.714286
41    HESM        12          17           0.705882
5     DGLY        14          20           0.700000
6     LORL        14          20           0.700000
347   SCWX         9          13           0.692308
265    DDS         9          13           0.692308
238   IRTC         9          13           0.692308
326   GLPI         9          13           0.692308
208    MIK         9          13           0.692308
215    MFA         9          13           0.692308
57    DLTH        11          16           0.687500
51    RIOT        11          16           0.687500
10     CAL        13          19           0.684211
16     PTN        13          19           0.684211
1     CETX        19          28           0.678571
22    AXLA        12          18           0.666667
29    ADES        12          18           0.666667
106    RHP        10          15           0.666667
413    GGN         8          12           0.666667
201   ETON        10          15           0.666667
379    MBI         8          12           0.666667
173   LMFA        10          15           0.666667
134   GIII        10          15           0.666667
149    RCL        10          15           0.666667
99    PBYI        10          15           0.666667
500    ZUO         8          12           0.666667
464    PEB         8          12           0.666667
39     PDD        12          18           0.666667
430   ENDP         8          12           0.666667
146   SSSS        10          15           0.666667
9     CVEO        13          20           0.650000
15    REPL        13          20           0.650000
8     MVIS        13          20           0.650000
17     CYH        13          20           0.650000
78     PRO        11          17           0.647059

In [ ]:
noonto4.to_csv('noonto4stocks.csv', index = False)